// crash_analyzer/constants.rs — 崩溃原因枚举与默认路径常量
// 注意：用字符串作为 key，Rust 改为 enum，通过 as_str() 提供中文描述

use std::path::PathBuf;

/// 默认 .minecraft 目录：用户主目录下 .minecraft
pub fn default_minecraft_dir() -> PathBuf {
    dirs::home_dir()
        .map(|h| h.join(".minecraft"))
        .unwrap_or_else(|| PathBuf::from(".minecraft"))
}

/// 崩溃原因枚举
/// 用字符串值（中文描述）作为 Map key，Rust 用 enum + as_str() 实现
#[derive(Clone, Debug, PartialEq, Eq, Hash)]
pub enum CrashReason {
    JavaVersionTooHigh,
    ModFileExtracted,
    MixinBootstrapError,
    OutOfMemory,
    UsingJDK,
    UsingOpenJ9,
    JavaTooOld,
    ModDuplicateModFiles,
    ModRequiresJava11,
    ModMissingDependency,
    ModIncompatible,
    ModMissingOrIncompatible,
    ModCrashed,
    ModNoInfo,
    ModMixinError,
    ModNameContainsSpecialChars,
    ModNameDuplicate,
    OptiFineIncompatible,
    AMDDriverCrash,
    NVidiaDriverCrash,
    IntelDriverCrash,
    PixelFormatNotAccelerated,
    ManuallyTriggeredCrash,
    OptiFineMissingForge,
    ShadersModWithOptiFine,
    ForgeMissing,
    FabricCrash,
    FabricModCrash,
    ForgeCrash,
    ModLoaderVersionIncompatible,
    NightConfigBug,
    OpenJ9Crash,
    OpenGL1282Error,
    ModIdConflict,
    InvalidPath,
    ModCyclicIssue,
    SecurityException,
    NativeLinkError,
    Unknown,
    JavaArgsError,
    GpuNoOpenGL,
    JavaVersionIncompatible,
    Java32Bit,
    ModConfigCrash,
    ModLoaderError,
    ModInitError,
    StackKeywordFound,
    StackModNameFound,
    SuspectedModCrash,
    ShortLogOutput,
    BlockCrash,
    EntityCrash,
    MultipleForge,
    TooManyMods,
    NoAnalysisFiles,
    TextureTooLarge,
    OptiFineCannotLoadWorld,
}

impl CrashReason {
    /// 返回面向用户的中文描述
    pub fn as_str(&self) -> &'static str {
        match self {
            Self::JavaVersionTooHigh => "Java版本过高",
            Self::ModFileExtracted => "Mod文件被解压",
            Self::MixinBootstrapError => "Mixin引导失败",
            Self::OutOfMemory => "内存不足",
            Self::UsingJDK => "使用JDK",
            Self::UsingOpenJ9 => "使用OpenJ9",
            Self::JavaTooOld => "Java版本过旧",
            Self::ModDuplicateModFiles => "Mod重复文件",
            Self::ModRequiresJava11 => "Mod需要Java11",
            Self::ModMissingDependency => "Mod缺少前置或MC版本错误",
            Self::ModIncompatible => "Mod不兼容",
            Self::ModMissingOrIncompatible => "Mod缺失或不兼容",
            Self::ModCrashed => "Mod崩溃",
            Self::ModNoInfo => "Mod无信息",
            Self::ModMixinError => "Mod Mixin错误",
            Self::ModNameContainsSpecialChars => "Mod名称包含特殊字符",
            Self::ModNameDuplicate => "Mod名称重复",
            Self::OptiFineIncompatible => "OptiFine不兼容",
            Self::AMDDriverCrash => "AMD驱动崩溃",
            Self::NVidiaDriverCrash => "NVIDIA驱动崩溃",
            Self::IntelDriverCrash => "Intel驱动崩溃",
            Self::PixelFormatNotAccelerated => "像素格式未加速",
            Self::ManuallyTriggeredCrash => "手动触发崩溃",
            Self::OptiFineMissingForge => "OptiFine缺少Forge",
            Self::ShadersModWithOptiFine => "ShadersMod与OptiFine冲突",
            Self::ForgeMissing => "Forge缺失",
            Self::FabricCrash => "Fabric崩溃",
            Self::FabricModCrash => "Fabric Mod崩溃",
            Self::ForgeCrash => "Forge崩溃",
            Self::ModLoaderVersionIncompatible => "Mod加载器版本不兼容",
            Self::NightConfigBug => "NightConfig Bug",
            Self::OpenJ9Crash => "OpenJ9崩溃",
            Self::OpenGL1282Error => "OpenGL 1282错误",
            Self::ModIdConflict => "Mod ID冲突",
            Self::InvalidPath => "无效路径",
            Self::ModCyclicIssue => "Mod循环问题",
            Self::SecurityException => "安全异常",
            Self::NativeLinkError => "本地库加载失败",
            Self::Unknown => "未知错误",
            Self::JavaArgsError => "Java虚拟机参数有误",
            Self::GpuNoOpenGL => "显卡不支持OpenGL",
            Self::JavaVersionIncompatible => "Java版本不兼容",
            Self::Java32Bit => "使用32位Java导致JVM无法分配足够多的内存",
            Self::ModConfigCrash => "Mod配置文件导致游戏崩溃",
            Self::ModLoaderError => "Mod加载器报错",
            Self::ModInitError => "Mod初始化失败",
            Self::StackKeywordFound => "堆栈分析发现关键字",
            Self::StackModNameFound => "堆栈分析发现Mod名称",
            Self::SuspectedModCrash => "怀疑Mod导致游戏崩溃",
            Self::ShortLogOutput => "极短的程序输出",
            Self::BlockCrash => "特定方块导致崩溃",
            Self::EntityCrash => "特定实体导致崩溃",
            Self::MultipleForge => "版本Json中存在多个Forge",
            Self::TooManyMods => "Mod过多导致超出ID限制",
            Self::NoAnalysisFiles => "没有可用的分析文件",
            Self::TextureTooLarge => "材质过大或显卡配置不足",
            Self::OptiFineCannotLoadWorld => "OptiFine导致无法加载世界",
        }
    }
}
